### ISSUE TITLE
no such table after install

### ISSUE THREAD

**Issue by chang-zhao** [hafron/dokuwiki-plugin-proza#1]
Trying PROZANAV I get
redirected to
de/proza/events/state/0/coordinator/schmucker
and error
SQLite error(1): no such table: events Query: ALTER TABLE events RENAME TO eventsbackup

**Comment by hafron** [comment]
On 16.02.2016 15:54, Chang Zhao wrote:
> Trying PROZANAV I get
> redirected to
> de/proza/events/state/0/coordinator/schmucker
> and error
> SQLite error(1): no such table: events Query: ALTER TABLE events RENAME
> TO eventsbackup
Try with the newest version. Make soure that you have at least one group 
before adding tasks.
